#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCafe.DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyQuanCafe")]
	public partial class QuanLyQuanCafeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertThucPham(ThucPham instance);
    partial void UpdateThucPham(ThucPham instance);
    partial void DeleteThucPham(ThucPham instance);
    partial void InsertBan(Ban instance);
    partial void UpdateBan(Ban instance);
    partial void DeleteBan(Ban instance);
    partial void InsertChiTietHoaDon(ChiTietHoaDon instance);
    partial void UpdateChiTietHoaDon(ChiTietHoaDon instance);
    partial void DeleteChiTietHoaDon(ChiTietHoaDon instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertKhuVuc(KhuVuc instance);
    partial void UpdateKhuVuc(KhuVuc instance);
    partial void DeleteKhuVuc(KhuVuc instance);
    partial void InsertLoaiThucPham(LoaiThucPham instance);
    partial void UpdateLoaiThucPham(LoaiThucPham instance);
    partial void DeleteLoaiThucPham(LoaiThucPham instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public QuanLyQuanCafeDataContext() : 
				base(global::QuanLyQuanCafe.DAO.Properties.Settings.Default.QuanLyQuanCafeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyQuanCafeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyQuanCafeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyQuanCafeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyQuanCafeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ThucPham> ThucPhams
		{
			get
			{
				return this.GetTable<ThucPham>();
			}
		}
		
		public System.Data.Linq.Table<Ban> Bans
		{
			get
			{
				return this.GetTable<Ban>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this.GetTable<ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<KhuVuc> KhuVucs
		{
			get
			{
				return this.GetTable<KhuVuc>();
			}
		}
		
		public System.Data.Linq.Table<LoaiThucPham> LoaiThucPhams
		{
			get
			{
				return this.GetTable<LoaiThucPham>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThucPham")]
	public partial class ThucPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maTP;
		
		private int _maLoaiTP;
		
		private string _tenTP;
		
		private string _dvt;
		
		private System.Nullable<decimal> _donGia;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
		private EntityRef<LoaiThucPham> _LoaiThucPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTPChanging(int value);
    partial void OnmaTPChanged();
    partial void OnmaLoaiTPChanging(int value);
    partial void OnmaLoaiTPChanged();
    partial void OntenTPChanging(string value);
    partial void OntenTPChanged();
    partial void OndvtChanging(string value);
    partial void OndvtChanged();
    partial void OndonGiaChanging(System.Nullable<decimal> value);
    partial void OndonGiaChanged();
    #endregion
		
		public ThucPham()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			this._LoaiThucPham = default(EntityRef<LoaiThucPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maTP
		{
			get
			{
				return this._maTP;
			}
			set
			{
				if ((this._maTP != value))
				{
					this.OnmaTPChanging(value);
					this.SendPropertyChanging();
					this._maTP = value;
					this.SendPropertyChanged("maTP");
					this.OnmaTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiTP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maLoaiTP
		{
			get
			{
				return this._maLoaiTP;
			}
			set
			{
				if ((this._maLoaiTP != value))
				{
					if (this._LoaiThucPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiTPChanging(value);
					this.SendPropertyChanging();
					this._maLoaiTP = value;
					this.SendPropertyChanged("maLoaiTP");
					this.OnmaLoaiTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTP", DbType="NVarChar(100)")]
		public string tenTP
		{
			get
			{
				return this._tenTP;
			}
			set
			{
				if ((this._tenTP != value))
				{
					this.OntenTPChanging(value);
					this.SendPropertyChanging();
					this._tenTP = value;
					this.SendPropertyChanged("tenTP");
					this.OntenTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dvt", DbType="NVarChar(50)")]
		public string dvt
		{
			get
			{
				return this._dvt;
			}
			set
			{
				if ((this._dvt != value))
				{
					this.OndvtChanging(value);
					this.SendPropertyChanging();
					this._dvt = value;
					this.SendPropertyChanged("dvt");
					this.OndvtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThucPham_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="maTP", OtherKey="maTP")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThucPham_ThucPham", Storage="_LoaiThucPham", ThisKey="maLoaiTP", OtherKey="maLoaiTP", IsForeignKey=true)]
		public LoaiThucPham LoaiThucPham
		{
			get
			{
				return this._LoaiThucPham.Entity;
			}
			set
			{
				LoaiThucPham previousValue = this._LoaiThucPham.Entity;
				if (((previousValue != value) 
							|| (this._LoaiThucPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiThucPham.Entity = null;
						previousValue.ThucPhams.Remove(this);
					}
					this._LoaiThucPham.Entity = value;
					if ((value != null))
					{
						value.ThucPhams.Add(this);
						this._maLoaiTP = value.maLoaiTP;
					}
					else
					{
						this._maLoaiTP = default(int);
					}
					this.SendPropertyChanged("LoaiThucPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.ThucPham = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.ThucPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ban")]
	public partial class Ban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maBan;
		
		private int _maKhuVuc;
		
		private string _tenBan;
		
		private string _trangThai;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntityRef<KhuVuc> _KhuVuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaBanChanging(int value);
    partial void OnmaBanChanged();
    partial void OnmaKhuVucChanging(int value);
    partial void OnmaKhuVucChanged();
    partial void OntenBanChanging(string value);
    partial void OntenBanChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    #endregion
		
		public Ban()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._KhuVuc = default(EntityRef<KhuVuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maBan
		{
			get
			{
				return this._maBan;
			}
			set
			{
				if ((this._maBan != value))
				{
					this.OnmaBanChanging(value);
					this.SendPropertyChanging();
					this._maBan = value;
					this.SendPropertyChanged("maBan");
					this.OnmaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhuVuc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maKhuVuc
		{
			get
			{
				return this._maKhuVuc;
			}
			set
			{
				if ((this._maKhuVuc != value))
				{
					if (this._KhuVuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhuVucChanging(value);
					this.SendPropertyChanging();
					this._maKhuVuc = value;
					this.SendPropertyChanged("maKhuVuc");
					this.OnmaKhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenBan", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string tenBan
		{
			get
			{
				return this._tenBan;
			}
			set
			{
				if ((this._tenBan != value))
				{
					this.OntenBanChanging(value);
					this.SendPropertyChanging();
					this._tenBan = value;
					this.SendPropertyChanged("tenBan");
					this.OntenBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="maBan", OtherKey="maBan")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_HoaDon", Storage="_HoaDons", ThisKey="maBan", OtherKey="maBan")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuVuc_Ban", Storage="_KhuVuc", ThisKey="maKhuVuc", OtherKey="maKhuVuc", IsForeignKey=true)]
		public KhuVuc KhuVuc
		{
			get
			{
				return this._KhuVuc.Entity;
			}
			set
			{
				KhuVuc previousValue = this._KhuVuc.Entity;
				if (((previousValue != value) 
							|| (this._KhuVuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhuVuc.Entity = null;
						previousValue.Bans.Remove(this);
					}
					this._KhuVuc.Entity = value;
					if ((value != null))
					{
						value.Bans.Add(this);
						this._maKhuVuc = value.maKhuVuc;
					}
					else
					{
						this._maKhuVuc = default(int);
					}
					this.SendPropertyChanged("KhuVuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Ban = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Ban = null;
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Ban = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Ban = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHoaDon")]
	public partial class ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCTHD;
		
		private int _maBan;
		
		private int _maTP;
		
		private System.Nullable<decimal> _donGia;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<decimal> _thanhTien;
		
		private EntityRef<Ban> _Ban;
		
		private EntityRef<ThucPham> _ThucPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCTHDChanging(int value);
    partial void OnmaCTHDChanged();
    partial void OnmaBanChanging(int value);
    partial void OnmaBanChanged();
    partial void OnmaTPChanging(int value);
    partial void OnmaTPChanged();
    partial void OndonGiaChanging(System.Nullable<decimal> value);
    partial void OndonGiaChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OnthanhTienChanging(System.Nullable<decimal> value);
    partial void OnthanhTienChanged();
    #endregion
		
		public ChiTietHoaDon()
		{
			this._Ban = default(EntityRef<Ban>);
			this._ThucPham = default(EntityRef<ThucPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCTHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCTHD
		{
			get
			{
				return this._maCTHD;
			}
			set
			{
				if ((this._maCTHD != value))
				{
					this.OnmaCTHDChanging(value);
					this.SendPropertyChanging();
					this._maCTHD = value;
					this.SendPropertyChanged("maCTHD");
					this.OnmaCTHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maBan
		{
			get
			{
				return this._maBan;
			}
			set
			{
				if ((this._maBan != value))
				{
					if (this._Ban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaBanChanging(value);
					this.SendPropertyChanging();
					this._maBan = value;
					this.SendPropertyChanged("maBan");
					this.OnmaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maTP
		{
			get
			{
				return this._maTP;
			}
			set
			{
				if ((this._maTP != value))
				{
					if (this._ThucPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaTPChanging(value);
					this.SendPropertyChanging();
					this._maTP = value;
					this.SendPropertyChanged("maTP");
					this.OnmaTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> thanhTien
		{
			get
			{
				return this._thanhTien;
			}
			set
			{
				if ((this._thanhTien != value))
				{
					this.OnthanhTienChanging(value);
					this.SendPropertyChanging();
					this._thanhTien = value;
					this.SendPropertyChanged("thanhTien");
					this.OnthanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_ChiTietHoaDon", Storage="_Ban", ThisKey="maBan", OtherKey="maBan", IsForeignKey=true)]
		public Ban Ban
		{
			get
			{
				return this._Ban.Entity;
			}
			set
			{
				Ban previousValue = this._Ban.Entity;
				if (((previousValue != value) 
							|| (this._Ban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ban.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._Ban.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._maBan = value.maBan;
					}
					else
					{
						this._maBan = default(int);
					}
					this.SendPropertyChanged("Ban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThucPham_ChiTietHoaDon", Storage="_ThucPham", ThisKey="maTP", OtherKey="maTP", IsForeignKey=true)]
		public ThucPham ThucPham
		{
			get
			{
				return this._ThucPham.Entity;
			}
			set
			{
				ThucPham previousValue = this._ThucPham.Entity;
				if (((previousValue != value) 
							|| (this._ThucPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThucPham.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._ThucPham.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._maTP = value.maTP;
					}
					else
					{
						this._maTP = default(int);
					}
					this.SendPropertyChanged("ThucPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHD;
		
		private int _maNhanVien;
		
		private int _maBan;
		
		private System.DateTime _ngayLap;
		
		private System.Nullable<decimal> _phuThu;
		
		private string _giamGia;
		
		private System.Nullable<int> _maKH;
		
		private decimal _tongTien;
		
		private System.Nullable<bool> _checkout;
		
		private EntityRef<Ban> _Ban;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDChanging(int value);
    partial void OnmaHDChanged();
    partial void OnmaNhanVienChanging(int value);
    partial void OnmaNhanVienChanged();
    partial void OnmaBanChanging(int value);
    partial void OnmaBanChanged();
    partial void OnngayLapChanging(System.DateTime value);
    partial void OnngayLapChanged();
    partial void OnphuThuChanging(System.Nullable<decimal> value);
    partial void OnphuThuChanged();
    partial void OngiamGiaChanging(string value);
    partial void OngiamGiaChanged();
    partial void OnmaKHChanging(System.Nullable<int> value);
    partial void OnmaKHChanged();
    partial void OntongTienChanging(decimal value);
    partial void OntongTienChanged();
    partial void OncheckoutChanging(System.Nullable<bool> value);
    partial void OncheckoutChanged();
    #endregion
		
		public HoaDon()
		{
			this._Ban = default(EntityRef<Ban>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maBan
		{
			get
			{
				return this._maBan;
			}
			set
			{
				if ((this._maBan != value))
				{
					if (this._Ban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaBanChanging(value);
					this.SendPropertyChanging();
					this._maBan = value;
					this.SendPropertyChanged("maBan");
					this.OnmaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="Date NOT NULL")]
		public System.DateTime ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phuThu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> phuThu
		{
			get
			{
				return this._phuThu;
			}
			set
			{
				if ((this._phuThu != value))
				{
					this.OnphuThuChanging(value);
					this.SendPropertyChanging();
					this._phuThu = value;
					this.SendPropertyChanged("phuThu");
					this.OnphuThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giamGia", DbType="NVarChar(4)")]
		public string giamGia
		{
			get
			{
				return this._giamGia;
			}
			set
			{
				if ((this._giamGia != value))
				{
					this.OngiamGiaChanging(value);
					this.SendPropertyChanging();
					this._giamGia = value;
					this.SendPropertyChanged("giamGia");
					this.OngiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="Int")]
		public System.Nullable<int> maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTien", DbType="Decimal(18,0) NOT NULL")]
		public decimal tongTien
		{
			get
			{
				return this._tongTien;
			}
			set
			{
				if ((this._tongTien != value))
				{
					this.OntongTienChanging(value);
					this.SendPropertyChanging();
					this._tongTien = value;
					this.SendPropertyChanged("tongTien");
					this.OntongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkout", DbType="Bit")]
		public System.Nullable<bool> checkout
		{
			get
			{
				return this._checkout;
			}
			set
			{
				if ((this._checkout != value))
				{
					this.OncheckoutChanging(value);
					this.SendPropertyChanging();
					this._checkout = value;
					this.SendPropertyChanged("checkout");
					this.OncheckoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_HoaDon", Storage="_Ban", ThisKey="maBan", OtherKey="maBan", IsForeignKey=true)]
		public Ban Ban
		{
			get
			{
				return this._Ban.Entity;
			}
			set
			{
				Ban previousValue = this._Ban.Entity;
				if (((previousValue != value) 
							|| (this._Ban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ban.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._Ban.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maBan = value.maBan;
					}
					else
					{
						this._maBan = default(int);
					}
					this.SendPropertyChanged("Ban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_KhachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maKH;
		
		private string _tenKH;
		
		private System.Nullable<int> _diemTichLuy;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(int value);
    partial void OnmaKHChanged();
    partial void OntenKHChanging(string value);
    partial void OntenKHChanged();
    partial void OndiemTichLuyChanging(System.Nullable<int> value);
    partial void OndiemTichLuyChanged();
    #endregion
		
		public KhachHang()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKH", DbType="NVarChar(100)")]
		public string tenKH
		{
			get
			{
				return this._tenKH;
			}
			set
			{
				if ((this._tenKH != value))
				{
					this.OntenKHChanging(value);
					this.SendPropertyChanging();
					this._tenKH = value;
					this.SendPropertyChanged("tenKH");
					this.OntenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemTichLuy", DbType="Int")]
		public System.Nullable<int> diemTichLuy
		{
			get
			{
				return this._diemTichLuy;
			}
			set
			{
				if ((this._diemTichLuy != value))
				{
					this.OndiemTichLuyChanging(value);
					this.SendPropertyChanging();
					this._diemTichLuy = value;
					this.SendPropertyChanged("diemTichLuy");
					this.OndiemTichLuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_HoaDons", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuVuc")]
	public partial class KhuVuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maKhuVuc;
		
		private string _tenKhuVuc;
		
		private string _trangThai;
		
		private System.Nullable<int> _soLuongBan;
		
		private EntitySet<Ban> _Bans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhuVucChanging(int value);
    partial void OnmaKhuVucChanged();
    partial void OntenKhuVucChanging(string value);
    partial void OntenKhuVucChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OnsoLuongBanChanging(System.Nullable<int> value);
    partial void OnsoLuongBanChanged();
    #endregion
		
		public KhuVuc()
		{
			this._Bans = new EntitySet<Ban>(new Action<Ban>(this.attach_Bans), new Action<Ban>(this.detach_Bans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhuVuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maKhuVuc
		{
			get
			{
				return this._maKhuVuc;
			}
			set
			{
				if ((this._maKhuVuc != value))
				{
					this.OnmaKhuVucChanging(value);
					this.SendPropertyChanging();
					this._maKhuVuc = value;
					this.SendPropertyChanged("maKhuVuc");
					this.OnmaKhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhuVuc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenKhuVuc
		{
			get
			{
				return this._tenKhuVuc;
			}
			set
			{
				if ((this._tenKhuVuc != value))
				{
					this.OntenKhuVucChanging(value);
					this.SendPropertyChanging();
					this._tenKhuVuc = value;
					this.SendPropertyChanged("tenKhuVuc");
					this.OntenKhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongBan", DbType="Int")]
		public System.Nullable<int> soLuongBan
		{
			get
			{
				return this._soLuongBan;
			}
			set
			{
				if ((this._soLuongBan != value))
				{
					this.OnsoLuongBanChanging(value);
					this.SendPropertyChanging();
					this._soLuongBan = value;
					this.SendPropertyChanged("soLuongBan");
					this.OnsoLuongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuVuc_Ban", Storage="_Bans", ThisKey="maKhuVuc", OtherKey="maKhuVuc")]
		public EntitySet<Ban> Bans
		{
			get
			{
				return this._Bans;
			}
			set
			{
				this._Bans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bans(Ban entity)
		{
			this.SendPropertyChanging();
			entity.KhuVuc = this;
		}
		
		private void detach_Bans(Ban entity)
		{
			this.SendPropertyChanging();
			entity.KhuVuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiThucPham")]
	public partial class LoaiThucPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maLoaiTP;
		
		private string _tenLoaiTP;
		
		private EntitySet<ThucPham> _ThucPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiTPChanging(int value);
    partial void OnmaLoaiTPChanged();
    partial void OntenLoaiTPChanging(string value);
    partial void OntenLoaiTPChanged();
    #endregion
		
		public LoaiThucPham()
		{
			this._ThucPhams = new EntitySet<ThucPham>(new Action<ThucPham>(this.attach_ThucPhams), new Action<ThucPham>(this.detach_ThucPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiTP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maLoaiTP
		{
			get
			{
				return this._maLoaiTP;
			}
			set
			{
				if ((this._maLoaiTP != value))
				{
					this.OnmaLoaiTPChanging(value);
					this.SendPropertyChanging();
					this._maLoaiTP = value;
					this.SendPropertyChanged("maLoaiTP");
					this.OnmaLoaiTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoaiTP", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenLoaiTP
		{
			get
			{
				return this._tenLoaiTP;
			}
			set
			{
				if ((this._tenLoaiTP != value))
				{
					this.OntenLoaiTPChanging(value);
					this.SendPropertyChanging();
					this._tenLoaiTP = value;
					this.SendPropertyChanged("tenLoaiTP");
					this.OntenLoaiTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThucPham_ThucPham", Storage="_ThucPhams", ThisKey="maLoaiTP", OtherKey="maLoaiTP")]
		public EntitySet<ThucPham> ThucPhams
		{
			get
			{
				return this._ThucPhams;
			}
			set
			{
				this._ThucPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThucPhams(ThucPham entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThucPham = this;
		}
		
		private void detach_ThucPhams(ThucPham entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThucPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNhanVien;
		
		private string _hoLot;
		
		private string _ten;
		
		private string _soCMND;
		
		private string _sdt;
		
		private string _diaChi;
		
		private string _gioiTinh;
		
		private string _chucVu;
		
		private System.DateTime _ngayLam;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(int value);
    partial void OnmaNhanVienChanged();
    partial void OnhoLotChanging(string value);
    partial void OnhoLotChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnsoCMNDChanging(string value);
    partial void OnsoCMNDChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnchucVuChanging(string value);
    partial void OnchucVuChanged();
    partial void OnngayLamChanging(System.DateTime value);
    partial void OnngayLamChanged();
    #endregion
		
		public NhanVien()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoLot", DbType="NVarChar(100)")]
		public string hoLot
		{
			get
			{
				return this._hoLot;
			}
			set
			{
				if ((this._hoLot != value))
				{
					this.OnhoLotChanging(value);
					this.SendPropertyChanging();
					this._hoLot = value;
					this.SendPropertyChanged("hoLot");
					this.OnhoLotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCMND", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string soCMND
		{
			get
			{
				return this._soCMND;
			}
			set
			{
				if ((this._soCMND != value))
				{
					this.OnsoCMNDChanging(value);
					this.SendPropertyChanging();
					this._soCMND = value;
					this.SendPropertyChanged("soCMND");
					this.OnsoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(20)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(100)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucVu", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string chucVu
		{
			get
			{
				return this._chucVu;
			}
			set
			{
				if ((this._chucVu != value))
				{
					this.OnchucVuChanging(value);
					this.SendPropertyChanging();
					this._chucVu = value;
					this.SendPropertyChanged("chucVu");
					this.OnchucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLam", DbType="Date NOT NULL")]
		public System.DateTime ngayLam
		{
			get
			{
				return this._ngayLam;
			}
			set
			{
				if ((this._ngayLam != value))
				{
					this.OnngayLamChanging(value);
					this.SendPropertyChanging();
					this._ngayLam = value;
					this.SendPropertyChanged("ngayLam");
					this.OnngayLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_HoaDons", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_TaiKhoans", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maTaiKhoan;
		
		private int _maNhanVien;
		
		private string _tenTaiKhoan;
		
		private string _matKhau;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTaiKhoanChanging(int value);
    partial void OnmaTaiKhoanChanged();
    partial void OnmaNhanVienChanging(int value);
    partial void OnmaNhanVienChanged();
    partial void OntenTaiKhoanChanging(string value);
    partial void OntenTaiKhoanChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maTaiKhoan
		{
			get
			{
				return this._maTaiKhoan;
			}
			set
			{
				if ((this._maTaiKhoan != value))
				{
					this.OnmaTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._maTaiKhoan = value;
					this.SendPropertyChanged("maTaiKhoan");
					this.OnmaTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="Int NOT NULL")]
		public int maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTaiKhoan", DbType="NVarChar(100)")]
		public string tenTaiKhoan
		{
			get
			{
				return this._tenTaiKhoan;
			}
			set
			{
				if ((this._tenTaiKhoan != value))
				{
					this.OntenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._tenTaiKhoan = value;
					this.SendPropertyChanged("tenTaiKhoan");
					this.OntenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="VarChar(50)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
