<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyQuanCafe" Class="QuanLyQuanCafeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TA_THAO\SQLEXPRESS;Initial Catalog=QuanLyQuanCafe;Integrated Security=True" SettingsObjectName="QuanLyQuanCafe.DAO.Properties.Settings" SettingsPropertyName="QuanLyQuanCafeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ThucPham" Member="ThucPhams">
    <Type Name="ThucPham">
      <Column Name="maTP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maLoaiTP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenTP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="dvt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="ThucPham_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="maTP" OtherKey="maTP" Type="ChiTietHoaDon" />
      <Association Name="LoaiThucPham_ThucPham" Member="LoaiThucPham" ThisKey="maLoaiTP" OtherKey="maLoaiTP" Type="LoaiThucPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ban" Member="Bans">
    <Type Name="Ban">
      <Column Name="maBan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maKhuVuc" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenBan" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Ban_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="maBan" OtherKey="maBan" Type="ChiTietHoaDon" />
      <Association Name="Ban_HoaDon" Member="HoaDons" ThisKey="maBan" OtherKey="maBan" Type="HoaDon" />
      <Association Name="KhuVuc_Ban" Member="KhuVuc" ThisKey="maKhuVuc" OtherKey="maKhuVuc" Type="KhuVuc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHoaDon" Member="ChiTietHoaDons">
    <Type Name="ChiTietHoaDon">
      <Column Name="maCTHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maBan" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maTP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="donGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thanhTien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Ban_ChiTietHoaDon" Member="Ban" ThisKey="maBan" OtherKey="maBan" Type="Ban" IsForeignKey="true" />
      <Association Name="ThucPham_ChiTietHoaDon" Member="ThucPham" ThisKey="maTP" OtherKey="maTP" Type="ThucPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maBan" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="phuThu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="giamGia" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="maKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="checkout" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Ban_HoaDon" Member="Ban" ThisKey="maBan" OtherKey="maBan" Type="Ban" IsForeignKey="true" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="maKH" OtherKey="maKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="maKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diemTichLuy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="maKH" OtherKey="maKH" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.KhuVuc" Member="KhuVucs">
    <Type Name="KhuVuc">
      <Column Name="maKhuVuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenKhuVuc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="soLuongBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhuVuc_Ban" Member="Bans" ThisKey="maKhuVuc" OtherKey="maKhuVuc" Type="Ban" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiThucPham" Member="LoaiThucPhams">
    <Type Name="LoaiThucPham">
      <Column Name="maLoaiTP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenLoaiTP" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="LoaiThucPham_ThucPham" Member="ThucPhams" ThisKey="maLoaiTP" OtherKey="maLoaiTP" Type="ThucPham" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="maNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hoLot" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soCMND" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="gioiTinh" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="chucVu" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLam" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="HoaDon" />
      <Association Name="NhanVien_TaiKhoan" Member="TaiKhoans" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="maTaiKhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenTaiKhoan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="matKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_TaiKhoan" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>